builds:
-
  goos:
    - darwin
    - linux
    - windows
  env:
    - CGO_ENABLED=0
  main: ./deplist/main.go
  binary: {{.Binary}}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brew:
  github:
    owner: markbates
    name: homebrew-tap
